### ISSUE TITLE
Memory leak on slow version of plotClippedPolyline

### ISSUE THREAD

**Issue by riccardomarotti** [jeremysanders/veusz#132] opened 2015-11-06 10:55 UTC
Adding points to a plot causes a growing memory consumption, leading to application crash.
Fortunately, this does not happen when using fast routines implemented in c++, so this isn't a big issue.

Our investigation led to `plotClippedPolyline` as a probable culprit (in `/veusz/utils/slowfuncs.py`).

**Comment by jeremysanders** [comment] 2015-11-14 13:20
Interesting - I can't reproduce this calling the function in a simple loop. If this function is at fault, it looks to be a PyQt bug, which may have been fixed in later versions.

**Comment by mythsmith** [comment] 2017-01-19 12:12
You can close it: it's gone long ago.

**Closed** 2017-01-28 16:00 UTC
